using System.IO.Compression;
using System.Text;
using System.Text.RegularExpressions;

namespace MeticulousResearch.Core.Export.Rendering;

/// <summary>
/// Normalizes format-writer output so two runs on identical input yield byte-identical files
/// (SPEC §3.4.2, TESTING-STRATEGY §4). Zip-based formats (DOCX/XLSX) have their per-entry timestamps
/// frozen to a fixed epoch; PDF output has its non-deterministic producer metadata (document ID and
/// creation/mod dates) replaced with fixed placeholders.
/// </summary>
internal static class DeterministicBytes
{
    private static readonly DateTimeOffset FixedEpoch = new(1980, 1, 1, 0, 0, 0, TimeSpan.Zero);

    /// <summary>Rewrites a zip (DOCX/XLSX) with fixed entry timestamps, preserving entry order.</summary>
    public static byte[] NormalizeZip(byte[] zipBytes)
    {
        using var source = new MemoryStream(zipBytes);
        using var archive = new ZipArchive(source, ZipArchiveMode.Read);
        using var output = new MemoryStream();
        using (var target = new ZipArchive(output, ZipArchiveMode.Create, leaveOpen: true))
        {
            // OpenXml can emit package parts in a non-deterministic order; sort by name so the
            // rewritten archive is byte-stable across runs. Entry order is irrelevant to OPC readers.
            foreach (var entry in archive.Entries.OrderBy(e => e.FullName, StringComparer.Ordinal))
            {
                var newEntry = target.CreateEntry(entry.FullName, CompressionLevel.Optimal);
                newEntry.LastWriteTime = FixedEpoch;
                using var entryStream = entry.Open();
                using var buffer = new MemoryStream();
                entryStream.CopyTo(buffer);
                var content = buffer.ToArray();

                // The OPC package-root relationship id (in "_rels/.rels") is auto-generated by
                // OpenXml as a random token and is not referenced by any part's XML, so it is safe
                // to renumber it deterministically. All other relationship ids are assigned
                // explicitly by the writers.
                if (entry.FullName == "_rels/.rels")
                    content = CanonicalizeRootRels(content);

                using var newStream = newEntry.Open();
                newStream.Write(content, 0, content.Length);
            }
        }

        return output.ToArray();
    }

    /// <summary>Renumbers the relationship ids in the package-root ".rels" to a stable sequence.</summary>
    private static byte[] CanonicalizeRootRels(byte[] relsBytes)
    {
        var text = Encoding.UTF8.GetString(relsBytes);
        var counter = 0;
        text = Regex.Replace(text, "Id=\"[^\"]*\"", _ => $"Id=\"rId{++counter}\"");
        return Encoding.UTF8.GetBytes(text);
    }

    /// <summary>Replaces non-deterministic PDF producer metadata (ID and dates) with fixed values.</summary>
    public static byte[] NormalizePdf(byte[] pdfBytes)
    {
        // Treat the byte stream as Latin1 so replacements preserve non-textual bytes intact.
        var text = Encoding.Latin1.GetString(pdfBytes);
        text = Regex.Replace(text, @"/ID\s*\[\s*<[0-9A-Fa-f]*>\s*<[0-9A-Fa-f]*>\s*\]", "/ID [<0><0>]");
        text = Regex.Replace(text, @"/CreationDate\s*\([^)]*\)", "/CreationDate (D:19800101000000Z)");
        text = Regex.Replace(text, @"/ModDate\s*\([^)]*\)", "/ModDate (D:19800101000000Z)");
        return Encoding.Latin1.GetBytes(text);
    }
}
